# GitHub Sponsors funding file
# This enables the "Sponsor" button on GitHub

# PayPal donation link
custom: ["https://www.paypal.com/donate/?business=GMQLBEXCL6DJY&no_recurring=0&currency_code=USD"]
